SRC = ft_display_file.c
OBJ = ft_display_file.o

CC = gcc

TARGET = ft_display_file

$(TARGET) : $(OBJ)
	$(CC) $(OBJ) -o $(TARGET)

clean: $(TARGET)
	rm -f $(OBJ)

fclean: clean
	rm -f $(TARGET)

all: $(TARGET)